### PR TITLE
Remove all uses of snapshot.exists in code base

### PR DESCRIPTION
**Pull request by b-butler**
## Description

Removes deprecated `Snapshot.exists` in tests and the code base.

## Motivation and context

Removes pytest warnings generated by `Snapshot.exists`.

## How has this been tested?

Existing tests pass (or should I have not tested locally yet).

## Change log

Not needed.

```

```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Review by joaander — APPROVED** [review]
Thanks!

**Comment by joaander** [comment]
We need to merge master up into this branch and resolve conflicts before we can merge it.

**Comment by lyrivera** [comment]
@b-butler  I checked out this branch locally and found that `snap.exists` is still being used within two of the jupyter notebooks within  `sphinc-doc/tutorial`:

- `sphinx-doc/tutorial/03-Custom-Actions-In-Python/04-Custom-Updater.ipynb`
- `sphinx-doc/tutorial/03-Custom-Actions-In-Python/06-Improving-Performance.ipynb`

Other than that, LGTM.

**Comment by joaander** [comment]
> @b-butler I checked out this branch locally and found that `snap.exists` is still being used within two of the jupyter notebooks within `sphinc-doc/tutorial`:
> 
> * `sphinx-doc/tutorial/03-Custom-Actions-In-Python/04-Custom-Updater.ipynb`
> * `sphinx-doc/tutorial/03-Custom-Actions-In-Python/06-Improving-Performance.ipynb`
> 
> Other than that, LGTM.

Thanks for the review. The tutorials need to be updated via a separate PR to the hoomd-examples repository.

**Comment by lyrivera** [comment]
> > @b-butler I checked out this branch locally and found that `snap.exists` is still being used within two of the jupyter notebooks within `sphinc-doc/tutorial`:
> > 
> > * `sphinx-doc/tutorial/03-Custom-Actions-In-Python/04-Custom-Updater.ipynb`
> > * `sphinx-doc/tutorial/03-Custom-Actions-In-Python/06-Improving-Performance.ipynb`
> > 
> > Other than that, LGTM.
> 
> Thanks for the review. The tutorials need to be updated via a separate PR to the hoomd-examples repository.

Sounds good. I'll approve then.

**Review by lyrivera — APPROVED** [review]

**Comment by joaander** [comment]
> > > @b-butler I checked out this branch locally and found that `snap.exists` is still being used within two of the jupyter notebooks within `sphinc-doc/tutorial`:
> > > 
> > > * `sphinx-doc/tutorial/03-Custom-Actions-In-Python/04-Custom-Updater.ipynb`
> > > * `sphinx-doc/tutorial/03-Custom-Actions-In-Python/06-Improving-Performance.ipynb`
> > > 
> > > Other than that, LGTM.
> > 
> > 
> > Thanks for the review. The tutorials need to be updated via a separate PR to the hoomd-examples repository.
> 
> Sounds good. I'll approve then.

Documented in: https://github.com/glotzerlab/hoomd-examples/issues/33

**Pull request merged**
