### PR TITLE
Remove custom action methods

### LINKED ISSUE #1648: Deprecate _InternalCustomUpdater.update, _InternalCustomTuner.tune, and _InternalCustomWriter.write
### Description

In a branch off `trunk-minor`, add deprecation warnings for:
* `_InternalCustomUpdater.update`.
* `_InternalCustomTuner.tune`.
* `_InternalCustomWriter.write`.
* `HDF5Log.write`.

After this branch is merged, remove these methods in a branch off `trunk-major`.

### Motivation and context

These methods are not logically consistent with the operations model in hoomd. `Simulation` is responsible for calling the operation's action at the appropriate time during the simulation loop. See https://github.com/glotzerlab/hoomd-blue/pull/1588#discussion_r1273668557 for additional context.

### PR DESCRIPTION
**Pull request by melodyyzh**
## Description

Removed the following methods in a branch off `trunk-major` after adding deprecation warnings in #1692 
* `_InternalCustomUpdater.update`.
* `_InternalCustomTuner.tune`.
* `_InternalCustomWriter.write`.
* `HDF5Log.write`.

## Motivation and context

Resolves #1648 

## How has this been tested?

Ran python tests on all the hoomd files, removed the wrap action act method in `custom_operation.py` to avoid the test calling the operation function and introduce error. 

## Change log 
```
Removed:

* ``_InternalCustomUpdater.update``.
  (`#1699 <https://github.com/glotzerlab/hoomd-blue/pull/1699>`__).
* ``_InternalCustomTuner.tune``.
  (`#1699 <https://github.com/glotzerlab/hoomd-blue/pull/1699>`__).  
* ``_InternalCustomWriter.write``.
  (`#1699 <https://github.com/glotzerlab/hoomd-blue/pull/1699>`__).
* ``HDF5Log.write``.
  (`#1699 <https://github.com/glotzerlab/hoomd-blue/pull/1699>`__).

```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Comment by melodyyzh** [comment]
The pytest failed at `test_hdf5.py` because it called `hdf5_writer.write()`, which was removed in this PR. Based on the conversation in PR #1588 , I am thinking we can either remove this line because timestep is optional, or replace it with `simulation.timestep` if it has been implemented in the documation?

**Comment by joaander** [comment]
You can remove `test_write_method` from `test_hdf5.py`. There is no need to test a method that does not exist.

**Review by tommy-waltmann — COMMENTED** [review]
Does the changelog need to be updated to say these methods were removed?

**Comment by joaander** [comment]
> Does the changelog need to be updated to say these methods were removed?

Yes. I handle changelog updates separately from pull requests in HOOMD-blue and will add this at some point after the PR is merged.

What does need to be added to this PR is an update to `migrating.rst` with a `Migrating to HOOMD-blue 5.0` section that notes the changes needed to user scripts.

**Comment by melodyyzh** [comment]
pre-commit.ci autofix

**Review by shihkual — APPROVED** [review]
LGTM!

**Review by tommy-waltmann — APPROVED** [review]

**Review by tcmoore3 — APPROVED** [review]
LGTM.

**Pull request merged**
