### PR TITLE
Only sync GSD files when writing out properties rather than per property

### PR DESCRIPTION
**Pull request by vyasr**
## Description

Instead of syncing the namelist each time a particular property's id is added, only sync at the end.

## Motivation and Context

On slow filesystems the fsync calls are extremely expensive and significantly degrade performance (by factors of >2).

## How Has This Been Tested?

Existing tests pass, ad hoc tests show substantial speed improvements.

## Change log

```
Update fsync calls for namelist to only call after all names are added to the list.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/hoomd-blue/blob/master/sphinx-doc/credits.rst).

### CODE REVIEW

**Comment by vyasr** [comment]
@joaander you may want to hold off merging this until the changes required to fix the tests on the GSD library are done.

**Comment by joaander** [comment]
Feel free to copy over the file after correcting the ifdefs. I didn't didn't transfer that fix to hoomd immediately because hoomd doesn't build on windows.

**Comment by vyasr** [comment]
I figured that's why you went ahead, but no harm in just dealing with the copy here. I'll do it once the other PR's tests pass.

**Comment by vyasr** [comment]
@joaander the file is updated. Merge when ready.

**Pull request merged**
