### PR TITLE
Fix double summation

### PR DESCRIPTION
**Pull request by jglaser**
## Description

Recompute all `Compute` values upon every run() command, so that they have current values when `prepRun()` is called in `System.cc`.

## Motivation and Context

With the current behavior, the following would happen with rigid bodies. When a run ends and another one is started, at the next `run()` command the log values of the potential energy and the computed pressure value would double, only at the initial time step. This introduces artifacts in the dynamics of constant pressure simulations with rigid bodies.

The underlying reason was that `ForceComposite` zeroes the net force and virial of constituent particles upon summing their forces and virials, but (of course) not the arrays of the individual `ForceCompute`s that contribute to the net force. `ForceComposite` caches the central particle forces and virials (it doesn't  recompute and thus zero the constituent particle net forces if the time step doesn't change), and when the net force gets summed upon `prepRun()`, the constraint force AND the constituent particle forces are added together. That way the central particle force and virial is counted twice.

A simple solution is to force reevaluation of **all** `Compute`s after a `run()` command, including the `ForceComposite` one.

Resolves: #380 

Note: I initially thought I wanted to avoid conflicts with changes in the `multi_gpu_npt` branch (#389), which is why I based the changes off of that branch. I can rebase if necessary, or we can simple merge the other branch first.

## How Has This Been Tested?

Added a unit test.

## Change log

```
Fix a bug where rigid body energy and pressure deviated on the first time step after `run()`.
Fix a bug which could lead to invalid MPI simulations with nlist.cell() and nlist.stencil()
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/hoomd-blue/blob/master/sphinx-doc/credits.rst).

### CODE REVIEW

**Comment by jglaser** [comment]
I also fixed a bug in the calculation in the ghost layer width of cell lists for MPI simulations, which looks like a serious oversight.

@joaander Please see 8693cd943fbd443472e0cd8483822f11622c2028

**Comment by mphoward** [comment]
The change you've made in 8693cd9 looks correct to me--I'm actually surprised nobody ever noticed this before.

What are the implications of the original code? You would have fewer cells covering the box than should be there based on `rlist` and the nominal cell width, but the rest of the cell list code also just takes this number of cells and runs with it (true cell width is computed separately). This means each cell is effectively larger than its nominal size, so you probably search a larger volume than required--this can happen anyway if the nominal width doesn't match the box. I don't think you would miss any ghost particles as these are stuffed into cells by the fractional coordinates & the number of cells rather than the cell size. So, if I haven't missed anything, this commit seems to fix a suboptimal cell list construction but there are probably not numerically incorrect results.

**Comment by jglaser** [comment]
> The change you've made in [8693cd9](https://github.com/glotzerlab/hoomd-blue/commit/8693cd943fbd443472e0cd8483822f11622c2028) looks correct to me--I'm actually surprised nobody ever noticed this before.
> 
> What are the implications of the original code? You would have fewer cells covering the box than should be there based on `rlist` and the nominal cell width, but the rest of the cell list code also just takes this number of cells and runs with it (true cell width is computed separately). This means each cell is effectively larger than its nominal size, so you probably search a larger volume than required--this can happen anyway if the nominal width doesn't match the box. I don't think you would miss any ghost particles as these are stuffed into cells by the fractional coordinates & the number of cells rather than the cell size. So, if I haven't missed anything, this commit seems to fix a suboptimal cell list construction but there are probably not numerically incorrect results.

Yes, that makes sense. However I noticed the `nlist.stencil()` unit test was reporting illegal memory accesses. The stencil assumes that there is at least one layer of ghost cells on every side.

**Comment by joaander** [comment]
Running `forceCompute` on all registered computes seems heavy handed. Could we introduce an alternate compute method or use a signal to only recompute only those that need to be?

**Comment by jglaser** [comment]
> Running `forceCompute` on all registered computes seems heavy handed. Could we introduce an alternate compute method or use a signal to only recompute only those that need to be?

Note that `forceCompute` typically only sets a flag to lazily force recomputation when the next `compute()` occurs. But agreed, we could introduce an additional method for classes that modify the netforce.

*Or*: we could wrap `Integrator::computeNetForce[GPU]()` inside a `compute`-like API, so it, too, does not get called twice when the forces are not updated. This might be solution for optimal performance with frequent `run()` commands.

**Comment by jglaser** [comment]
> > Running `forceCompute` on all registered computes seems heavy handed. Could we introduce an alternate compute method or use a signal to only recompute only those that need to be?
> 
> Note that `forceCompute` typically only sets a flag to lazily force recomputation when the next `compute()` occurs. But agreed, we could introduce an additional method for classes that modify the netforce.
> 
> _Or_: we could wrap `Integrator::computeNetForce[GPU]()` inside a `compute`-like API, so it, too, does not get called twice when the forces are not updated. This might be solution for optimal performance with frequent `run()` commands.

as we discussed, the best solution to this problem may be ignoring constituent particles in ComputeThermo

**Pull request merged**
