### PR TITLE
Use Warning consistently on instantiating a base class and remove redundant roles

### LINKED ISSUE #1307: Use Warning: to notify users about unusable base classes
## Description

Convert:
```
    Note:
        :py:class:`SomeClass` is the base class for all ....
        and provides common methods. Users should not instantiate this class
        directly.
```
to
```
Warning:
    ...
```

## Motivation and context

Make it more obvious that users can't use the class direclty.

### PR DESCRIPTION
**Pull request by b-butler**
## Description

Uses the Warning label for a warning to not directly instantiate a base class.
Also remove redundant roles and backticks.

## Motivation and context

Resolves #1307

## How has this been tested?

Documentation builds without warning

## Change log

```

```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Review by vyasr — APPROVED** [review]
Could you update the title to reflect that you've also updated roles? I did a double take when I first saw how many changes there were that didn't involve warnings.

**Comment by b-butler** [comment]
> Could you update the title to reflect that you've also updated roles? I did a double take when I first saw how many changes there were that didn't involve warnings.

Good point. I updated the name to reflect the dual nature of the PR.

**Review by joaander — APPROVED** [review]
Thanks!

**Comment by joaander** [comment]
Brandon, would you like to merge this before or after #1311?

**Comment by b-butler** [comment]
Before is fine. I will deal with merge conflicts.

**Pull request merged**
