### PR TITLE
Add CosineSquared pair potential

### PR DESCRIPTION
**Pull request by YouriRan**
## Description

Implement CosineSquared potential as described in [Cooke 2005](https://doi.org/10.1063/1.2135785). 

## Motivation and context

This implementation allows for the use of the Cosine Squared potential, generally used for coarse-grained simulation of membrane systems.

Resolves [#1106](https://github.com/glotzerlab/hoomd-blue/issues/1106).

## How has this been tested?

Tested to run locally on CPU. Documentation displays properly.

TODO: GPU & validation testing.

## Change log

```
Add hoomd/md/EvaluatorPairCosineSquared.h
Add hoomd/md/CosineSquaredDriverPotentialPairGPU.h
Modify hoomd/md/AllDriverPotentialPairGPU.cuh
Modify hoomd/md/AllPairPotentials.h
Modify hoomd/md/CMakeLists.txt
Modify hoomd/md/module-md.cc
Modify hoomd/md/pair/__init__.py
Modify hoomd/md/pair/pair.py
Modify sphinx-doc/module-md-pair.rst
Modify sphinx-doc/credits.rst
```

## Points of note

* Would someone be willing to check if the math in EvaluatorPairCosineSquared.h is implemented efficiently?

## Checklist:

- [ x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [ x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [ x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Comment by YouriRan** [comment]
Hi, I'm sorry, this is really the first time I'm contributing and I fudged up this pull request in rebasing. Sorry for that. The code does work on an up to date version for me locally, should I make a new pull request and try again or is there a way to fix this one?

**Comment by joaander** [comment]
@YouriRan I think all you need to do is merge master in to your branch:
```
git switch master
git pull
git switch cossq
git merge master
git push
```

**Comment by YouriRan** [comment]
Hi, could you start the unit tests?

**Comment by YouriRan** [comment]
Hello, some tests have been skipped, but I don't understand why. Could anyone help me with how to make sure they succeed?

**Comment by joaander** [comment]
We intentionally skip the longer running tests to reduce resource usage on the CI platform. I will enable these tests after the code has been reviewed and the pull request is nearly ready to merge.

**Comment by YouriRan** [comment]
Okay, thanks. Let me know if I need to do something.

**Comment by joaander** [comment]
As long as this pull request remains in a draft state, we assume it is not yet ready for review.

**Review by joaander — COMMENTED** [review]
Thanks, this looks a like a reasonable implementation of the given potential. Before I give it a full review, I'd like to understand the reasoning behind its implementation.
1) How much faster is the analytical implementation of this potential over a tabulated potential on a modern GPU?
2) How much faster is the combined WCA + cosine squared vs using pair.LJ for WCA and only computing the cosine squared term separately in this potential.
3) Are you aware of other HOOMD users that would like to make use of this potential?

**Review by pepak13 — APPROVED** [review]

**Pull request closed without merging**
