### PR TITLE
Mesh helfrich energy

### PR DESCRIPTION
**Pull request by SchoeniPhlippsn**
## Description

This adds a Helfrich potential which can be applied to the mesh data structure. 

## Motivation and context

This bending rigidity formulated by Helfrich allows for applying a bending modulus that closely behaves like a lipid mono-/bi-layer membrane represented by a particle mesh.

## How has this been tested?

I added pytests and used this potential in my current studies.

## Change log

```
Addition of a Helfrich mesh bending rigidity potential 
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.rst).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Comment by SchoeniPhlippsn** [comment]
This is the second bending rigidity. I decided to split them into two PRs because this potential is still very slow when used in parallel on GPU.

**Comment by SchoeniPhlippsn** [comment]
pre-commit.ci autofix

**Comment by SchoeniPhlippsn** [comment]
@joaander @tcmoore3 
Ready for review!

**Review by joaander — APPROVED** [review]
Thanks!

**Pull request merged**
