### PR TITLE
Fix misc documentation issues

### PR DESCRIPTION
**Pull request by joaander**
## Description

Fix documentation issues reported by users

## Motivation and Context

Resolves: #442, #439

## How Has This Been Tested?

Local sphinx documentation build

## Change log

```
* Clarify singularity image download documentation
* Correctly document the functional form of the Buckingham pair potential
* Correct typos in HPMC example snippets
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/hoomd-blue/blob/master/sphinx-doc/credits.rst).
- [ ] (Glotzer group members): I am a member of the [hoomd-contributors team](https://github.com/orgs/glotzerlab/teams/hoomd-contributors/members).

### CODE REVIEW

**Comment by lyrivera** [comment]
@joaander I recently noticed that the docstrings of the [hpmc.polyhedron](https://github.com/glotzerlab/hoomd-blue/blob/41d4845cb6273f2f1f56c71e587157cd8da850af/hoomd/hpmc/integrate.py#L1217) integrator says that only triangle meshes are supported but all the examples provide rectangular meshes. You may want to include that in this PR.

**Comment by j-proc** [comment]
This looks good to me provided the tests all pass. I suspect if they don't it will be another issue since it would not pertain to documentation. Re: example code `param` vs `params`, I know most of this will likely go away if proposed API changes are made in HOOMD v3. However, is there a way we can pull all the examples from the documentation and check for syntax errors without any actual HOOMD runs? I'm not aware of such a trick, so asking the more experienced. If useful, I'll make a proposal issue and of course accept these changes.

**Comment by lyrivera** [comment]
> This looks good to me provided the tests all pass. I suspect if they don't it will be another issue since it would not pertain to documentation. Re: example code `param` vs `params`, I know most of this will likely go away if proposed API changes are made in HOOMD v3. However, is there a way we can pull all the examples from the documentation and check for syntax errors without any actual HOOMD runs? I'm not aware of such a trick, so asking the more experienced. If useful, I'll make a proposal issue and of course accept these changes.

I've encountered this issue in other places before, so it would be really nice if it could be automated.

**Comment by joaander** [comment]
> > However, is there a way we can pull all the examples from the documentation and check for syntax errors without any actual HOOMD runs? I'm not aware of such a trick, so asking the more experienced. If useful, I'll make a proposal issue and of course accept these changes.
> 
> I've encountered this issue in other places before, so it would be really nice if it could be automated.

Yes, [there is a way](https://ipython.readthedocs.io/en/stable/sphinxext.html). I use it in GSD. from my experiences there, I don't think it would not be practical for HOOMD. 1) It would require that readthedocs build HOOMD from source which would require requesting a time limit extension from readthedocs. 2) Every example snippet would need to be a fully functioning hoomd simulation. 3) GPU examples would not be possible because readthedocs runs on CPUs in the cloud.

For v3, my current plan is to remove all of these error-prone example snippets and instead include at least one full jupyter notebook sample script for each class. Class documentation can link to the notebook example. See [fresnel's documentation](https://fresnel.readthedocs.io/en/stable/module-geometry.html#fresnel.geometry.ConvexPolyhedron) for an example of this pattern.

**Pull request merged**
