### PR TITLE
Remove unused r_on and default_r_on parameters.

### LINKED ISSUE #1047: Remove r_on for potentials that do not support "xplor" mode
## Description
Many potentials do not support the "xplor" energy/force shifting, but allow setting `default_r_on` and `obj.r_on[(type, type)]`. This does not make much sense as they can never be meaningfully set. I think removing the typeparameter and constructor argument would be best.

## Motivation and context
I believe this would increase the API coherence.

### PR DESCRIPTION
**Pull request by joaander**
## Description

Removed unused `r_on` and `default_r_on` parameters in MD pair forces.

## Motivation and context

Some potentials do not support xplor smoothing, so the `r_on` parameters are unused.

Resolves #1047 

## How has this been tested?

Existing unit tests pass.

I manually checked that `r_on` is indeed not present:
```
>>> nlist = hoomd.md.nlist.Cell(buffer=0.4)
>>> f = hoomd.md.pair.Table(nlist=nlist)
>>> f.r_on
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joaander/build/hoomd/hoomd/operation.py", line 57, in __getattr__
    raise AttributeError("Object {} has no attribute {}".format(
AttributeError: Object <class 'hoomd.md.pair.pair.Table'> has no attribute r_on
```

## Change log

```
Changed:

* Removed the `r_on` attribute and `default_r_on` constructor argument from pair potentials that do not use it.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

## Note

Merge after #1189

### CODE REVIEW

**Review by tommy-waltmann — COMMENTED** [review]
There was some discussion in #1047 about adding documentation explaining which smoothing modes are/aren't supported by which classes, and I think that would be a good idea to add here.

**Comment by joaander** [comment]
> There was some discussion in #1047 about adding documentation explaining which smoothing modes are/aren't supported by which classes, and I think that would be a good idea to add here.

Done.

**Comment by tommy-waltmann** [comment]
I see this done in every class except for `SLJ`, is that an error or it that because it will soon be removed?

**Comment by joaander** [comment]
> I see this done in every class except for `SLJ`, is that an error or it that because it will soon be removed?

SLJ will be removed in the February release: #1181

**Review by tommy-waltmann — APPROVED** [review]

**Pull request merged**
