### PR TITLE
Merge 64bit into depletants

### PR DESCRIPTION
**Pull request by joaander**
## Description

This PR merges #894 into #659. Most of the diff will be a duplicate of $#894. Look at the following commits to see the main changes done by the merge:

* b20d1c62d60df00411989524f6db5a65bd87470a

## Motivation and context

Once #894 is merged into master, we will need to merge it into `depletants_new`.

## How has this been tested?

I have not tested this except that it compiles. @jglaser can run his tests on this branch once it is working.

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Comment by joaander** [comment]
@jglaser I didn't follow some of the seeding strategies used in the `depletants_new` branch. Please check that I updated these appropriately in b20d1c62d60df00411989524f6db5a65bd87470a.

**Comment by joaander** [comment]
One set of tests is failing on this because it triggers an internal compiler error in gcc 4.8: https://dev.azure.com/glotzerlab/hoomd-blue/_build/results?buildId=10126&view=logs&j=48749ede-db32-5297-df2b-603e52cd1707&t=5aca2c17-154c-5058-38ca-9f73a076b402&l=2195

Perhaps it is time to finally drop support for that old compiler.

**Comment by joaander** [comment]
@jglaser once you review and approve the changes in b20d1c6, we can merge this into `depletants_new` and then merge that branch into `master`.

**Comment by jglaser** [comment]
I looked at b20d1c6 , and I believe it is correct.  I will be able to confirm numerical correctness once #923 is merged.

**Pull request merged**
