### PR TITLE
Feature/rename move ratio

### PR DESCRIPTION
**Pull request by vyasr**
## Description

This PR renames instance of `move_ratio` throughout HPMC to `*move_probability` to more accurately reflect the meaning of these parameters.

**I'm not quite sure how to handle `hpmc.update.Clusters`, which I have not yet changed.** There are multiple parameters and they each affect probabilities in different ways in different situations. I glanced at the C++ code, and offhand it seems like line reflections and pivots are applied per particle then swaps are applied to all types in a cluster, but I'll have to spend more than 5 minutes looking through that code to understand exactly how the different input probabilities factor in to the final move choice. Note that the validity of pivot moves depends on whether or not particles are anisotropic, and I don't think the type swaps are applied across all types, so all the parameters are somewhat conditional. If @jglaser or anyone else knows the answer offhand, I can apply the appropriate naming conventions.

**Update I'm going to avoid changing the cluster updater in this PR, so it should be ready for review.

## Motivation and context

Partially addresses #777 (update.Clusters will be handled separately at a later date).

## How has this been tested?

Covered by existing tests.

## Change log

None needed IMO.

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Comment by jglaser** [comment]
I suggest saving changes to `UpdaterClusters` for later. At present, they will only generate (even more) merge conflicts with ongoing work in #659 .

**Comment by vyasr** [comment]
That's fine with me, I've updated the PR description to reflect that `update.clusters` won't be changed in this PR. In that case, this PR is ready to review and merge.

**Review by joaander — APPROVED** [review]
Thanks!

**Pull request merged**
