### PR TITLE
Fix builds with ROCM 5.1.0.

### PR DESCRIPTION
**Pull request by joaander**
## Description

Make all changes needed to build HOOMD against ROCM 5.1.0.

## Motivation and context

These changes allow HOOMD to run on OLCF Crusher, the test system for Frontier.

## How has this been tested?

I executed the unit tests (ctest and pytest). The core and md test pass. I'm getting seg faults in the HPMC tests. Our immediate need is for MD simulations on Frontier, so let's merge this set of fixes now. I will revisit HPMC support in a later PR.

## Change log

```
Fixed:

* Compile without errors using `hipcc` and ROCM 5.1.0.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Comment by joaander** [comment]
https://github.com/glotzerlab/software/pull/263 includes the install script for the Crusher build environment.

**Comment by joaander** [comment]
#1479 documents the seg fault.

**Review by b-butler — APPROVED** [review]
:+1:

**Comment by joaander** [comment]
@pepak13 Let me know what you think.

**Review by pepak13 — APPROVED** [review]

**Pull request merged**
