### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by joaander**
## Description

Add the new HOOMD-blue logo to the documentation header and favicon. Add a logo download page where users can download the logo to display in their posters and presentations.

## Motivation and context

Users should be able to identify HOOMD-blue by a logo.

## How has this been tested?

* I rendered the documentation locally.
* I viewed GitHub's rendering of the README at: https://github.com/glotzerlab/hoomd-blue/tree/add-logo

## Change log

```
Added:

* New HOOMD-blue logo to the documentation.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Comment by joaander** [comment]
@b-butler Do you approve?

**Review by ispivack — APPROVED** [review]
The new logo looks great. It is an svg file, which is perfect.

**Review by b-butler — COMMENTED** [review]
LGTM. Glad to have the logo out there, :smile:

**Comment by bdice** [comment]
@joaander This new logo looks great! 💯 🚀

**Comment by joaander** [comment]
> @joaander This new logo looks great! 💯 🚀

Indeed it does.

**Pull request merged**
