### PR TITLE
Migrate particles using GPU kernels

### PR DESCRIPTION
**Pull request by jglaser**
## Description

Use GPU kernels to sort migrating particles.

## Motivation and Context

Currently we use a loop on the host. I don't remember for what reason, maybe it was originally faster that way. In any case, I had to fix a bug in the GPU code path that was commented out. These changes should reduce latency. Should be merged after #549.

Resolves: N/A

## How Has This Been Tested?

offline, unit test `md/test_communication`

## Change log

```
- Lower latency in MPI simulations on GPUs in particle migration
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/hoomd-blue/blob/master/sphinx-doc/credits.rst).

### CODE REVIEW

**Comment by mphoward** [comment]
fwiw, I am already doing this sorting on the GPU in the MPCD communicator. The much larger number of particles per rank in MPCD always made the GPU path more performant.

**Comment by joaander** [comment]
@jglaser Do you plan to update this for v3? Or should we close this PR?

**Comment by jglaser** [comment]
Not a priority for me right now.

**Comment by joaander** [comment]
Thanks for the update, I'll close it.

**Pull request closed without merging**
