### PR TITLE
Use neighbor fixed up for CUDA 11

### PR DESCRIPTION
**Pull request by mphoward**
## Description

CUDA 11 has CUB internal, so neighbor 0.2 needs to use this version rather than HOOMD's copy. This problem is already solved in neighbor 0.3 for HOOMD 3.x, which always uses `<cub/cub.cuh>`, but patches the issue for HOOMD 2.9. See:

https://github.com/mphowardlab/neighbor/commit/0956bd3ed4601a1793b7b2711af3b9880a88d8fc

## Motivation and Context

#680 

## How Has This Been Tested?

User confirmed that this fixed their compilation issue with CUDA 11.

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/hoomd-blue/blob/master/sphinx-doc/credits.rst).

### CODE REVIEW

**Comment by b-butler** [comment]
This seems to cause a bunch of tests on MacOS to fail.

**Comment by mphoward** [comment]
The macOS failures occur even on CPU builds and all stem from a numpy import error. This doesn't seem like it could be caused by this commit, honestly, so could you check your CI configuration?

**Comment by mphoward** [comment]
(The last two commits on maint have the same errors.)

**Comment by b-butler** [comment]
@mphoward you are correct, I should have checked Azure first. In that case, I don't have any other comments given the simple nature of the PR.

**Comment by joaander** [comment]
Sorry, I fixed the mac build errors on `next` but failed to backport those changes to `maint`. At this point we are only applying essential fixes to `maint` as we prepare for a 3.0 beta release soon so I'm not going to put too much effort into it.

I'm going to retarget this to a 2.9 branch so I don't need to keep dealing with merge conflicts as we merge fixes from `maint` all they way up to `feature/new-object-api`. I'll take care of duplicating any future fixes to ensure they make it into 3.0.

**Pull request merged**
