### PR TITLE
Add How To guide for molecular systems.

### PR DESCRIPTION
**Pull request by joaander**
## Description

Add a how to guide for molecular systems in molecular dynamics simulations.

## Motivation and context

This is a common question on the mailing list.

## How has this been tested?

I executed the example script locally.

## Change log

```
Added:

* Guide on how to model molecular systems.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Review by tommy-waltmann — COMMENTED** [review]
One thing to consider here is that having the "how to model molecular systems" howto nested inside a molecular dynamics section might make it harder for people to find what they're looking for.

**Comment by joaander** [comment]
> One thing to consider here is that having the "how to model molecular systems" howto nested inside a molecular dynamics section might make it harder for people to find what they're looking for.

Would you prefer a single page for all MD, MC, and other how tos?

**Comment by joaander** [comment]
> > One thing to consider here is that having the "how to model molecular systems" howto nested inside a molecular dynamics section might make it harder for people to find what they're looking for.

I moved the new documentation to `howto.rst` per your request. I still think that once we add a few dozen howtos that it will be difficult to find anything in such a long document. However, we can deal with that later.

**Comment by tommy-waltmann** [comment]
To more fully explain my suggestion from before, I was trying to suggest having a "HOW TO GUIDES" section heading in blue on the left sidebar (similar to "PYTHON API", "TUTORIALS", and "GETTING STARTED") and then under that section heading, have an entry for each how to guide (similar to how under PYTHON API, one can see hoomd hoomd.hpmc, hoomd.md).

That way people could more immediately see what they're looking for, instead of having to to know they need to click another "molecular dynamics" heading to reveal the howto guide they are looking for.

I don't know exactly how many how to guides we plan on putting in the documentation, but I see your point about the left panel looking a little too messy if we have a lot of them. I'd say if we plan on having <=10 how to guides, we don't need the extra level of organization.

We can organize them so its a bit easier to use now, or we can organize them so we don't have to re-organize in the future, It just depends on how many howto's we think we'll end up having after a while.

**Comment by joaander** [comment]
> > That way people could more immediately see what they're looking for, instead of having to to know they need to click another "molecular dynamics" heading to reveal the howto guide they are looking for.
> 
> OK, we can try this for now. As you say we can put only a small number on the left panel without making navigation difficult. Beyond that and people will need to use the main page table of contents, the index, or the search feature to find things.

FYI, the left panel contents already requires scrolling on 1080p displays and mobile devices. There is a small amount of space left on 1440p.

**Review by tommy-waltmann — APPROVED** [review]

**Pull request merged**
