### PR TITLE
Replace gsd log with logger

### LINKED ISSUE #1480: Inconsistent logger keyword argument name in write.GSD and write.Table
### Description

Deprecate the use of `write.GSD(..., log=log.Logger)` in place of `write.GSD(..., logger=log.Logger)` for consistency with `write.Table`.

### Motivation and context

Both `write.GSD` and `write.Table` accept `log.Logger` arguments to log simulation data. This argument is named `log` in the `GSD` writer and `logger` in the `Table` writer. For consistency and since we are providing a `Logger`, this argument should be named `logger`.

### PR DESCRIPTION
**Pull request by tcmoore3**
## Description

Renames `log` kwarg of `write.GSD` to `logger`. See #1481 and #1480.

## Motivation and context

Resolves #1480. 

## How has this been tested?

The unit tests should be sufficient.

## Change log

```
Rename `log` keyword argument and property of `write.GSD` to `logger`.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Review by joaander — CHANGES_REQUESTED** [review]
Update the unit tests so they pass. Also, the PR on `trunk-minor` should add `logger` and make it the default. The PR on `trunk-major` should remove the deprecated `log` and document it in `migrating.rst`.

**Comment by tcmoore3** [comment]
> Update the unit tests so they pass. Also, the PR on `trunk-minor` should add `logger` and make it the default. The PR on `trunk-major` should remove the deprecated `log` and document it in `migrating.rst`.

OK, I added the logger, made it the default, and raise DeprecationWarnings when users use `log` on the other PR. Should this info be in a new v3-to-v4 section of `migrating.rst`? Or instead should it go into `deprecated.rst?'

**Review by joaander — COMMENTED** [review]
Thanks! This is good as-is, however it will generate merge conflicts after #1481 is merged. Once #1481 is approved, please merge `rename-gsd-log` into this branch and resolve the conflicts. Then I will approve and merge.

**Comment by joaander** [comment]
@tcmoore3 It would seem that merging `rename-gsd-log` into this branch did not prevent merge conflicts. My apologies for suggesting this strategy. You will need to merge `trunk-major` into this branch and resolve conflicts.

**Review by joaander — APPROVED** [review]
Thanks!

**Pull request merged**
