### PR TITLE
Clarify rotational dof documentation.

### PR DESCRIPTION
**Pull request by joaander**
## Description

Explain the conditions under which MD integrators integrate the rotational degrees of freedom.

## Motivation and context

Some users expressed confusion on this topic. Existing documentation does not cover it.

## Change log

```
* Improve documentation.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Review by shihkual — COMMENTED** [review]
In the changes to the docstring of compute.py `\\frac{L_{x,i}^2}{I_{d,i}} & I^d_i > 0 \\\\`, does the calculation of rotational kinetic energy always consider the angular momentum in x direction only or it's just a typo?

**Comment by joaander** [comment]
> In the changes to the docstring of compute.py `\\frac{L_{x,i}^2}{I_{d,i}} & I^d_i > 0 \\\\`, does the calculation of rotational kinetic energy always consider the angular momentum in x direction only or it's just a typo?

Good catch, this is a typo.

**Review by b-butler — APPROVED** [review]
LGTM once `trunk-patch` is merged in so the pre-commit check passes.

**Review by shihkual — COMMENTED** [review]
Everything looks fine

**Review by shihkual — APPROVED** [review]

**Pull request merged**
