### PR TITLE
Tests for checking loggables match expected namespace

### LINKED ISSUE #922: Test for logging names
## Description

Each operation should have tests that 
1. Add it to a `Logger`
2. Check that the namespace is generated properly

## Motivation and context

On https://github.com/glotzerlab/hoomd-examples/pull/19 I found that the LJ pair energy quantity changed names. Unit tests in hoomd would detect regressions such as these.

### PR DESCRIPTION
**Pull request by Charlottez112**
## Description

This PR adds tests that check the names of the log gables match the expected namespace.

## Motivation and context

Resolves #922 

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Comment by Charlottez112** [comment]
I still need to add tests for several other classes that have loggables, but just wanted to push the current changes and have someone take a look if this is what we want. Also I'm not sure what's the most efficient way to test loggables related to `md.force.Force`, since it seems like there's no test specifically for it.

**Comment by joaander** [comment]
@b-butler should review these changes.

**Comment by Charlottez112** [comment]
There's not a pytest for `hpmc.integrate`, so I put the test that checks its loggable names in `test_compute_sdf.py`. And like I mentioned above, the loggables associated with `md.force.Force` are checked in 'test_potential.py'. Otherwise I think I've checked all loggables.

**Comment by joaander** [comment]
@Charlottez112 @b-butler I would like to see this completed and merged. Do you have any questions?

**Comment by Charlottez112** [comment]
> `type_shapes` is not implemented in the base class `HPMCIntegrator`. It is implemented only in those subclass integrators that support the protocol. 

Should we also add the `loggable` label under the `shape` parameters in the doc then? Because all other loggable quantities have a line like `(Loggable: category=”sequence”)`. Also I'm not sure where I should put the test for checking `type_shapes`.

**Comment by joaander** [comment]
> > `type_shapes` is not implemented in the base class `HPMCIntegrator`. It is implemented only in those subclass integrators that support the protocol.
> 
> Should we also add the `loggable` label under the `shape` parameters in the doc then? Because all other loggable quantities have a line like `(Loggable: category=”sequence”)`. Also I'm not sure where I should put the test for checking `type_shapes`.

Do not manually add the `Loggable:` documentation. The implemented `type_shapes` are defined as loggable with `@log(category='object', requires_run=True)`. These should get the automatically generated `Loggable:` documentation? @b-butler why aren't they?

You can add a new `test_` file and check the specific HPMC integrators that support `type_shapes` there.

**Comment by b-butler** [comment]
@joaander my guess is that since the property `type_shapes` exist in `HPMCIntegrator` that it is preventing the same property to show in the derived classes. This also may have something to do with the `show-inheritance` option.

**Comment by joaander** [comment]
> @joaander my guess is that since the property `type_shapes` exist in `HPMCIntegrator` that it is preventing the same property to show in the derived classes. This also may have something to do with the `show-inheritance` option.
> 
> This would mean the docstrings are correct but just not shown which is consistent with the current documentation.

Can we fix by removing the method from the base class?

**Comment by Charlottez112** [comment]
> You can add a new `test_` file and check the specific HPMC integrators that support `type_shapes` there.

I realized that I can still test this by just calling a specific subclass integrator, so I just put it in `test_shape.py` to let the tests past first. I'm not sure what else I need to do. It seems like we haven't decided what to do?

**Review by joaander — COMMENTED** [review]
@b-butler is the one with the change request, he needs to re-review.

**Review by b-butler — APPROVED** [review]
:+1:

**Pull request merged**
