### PR TITLE
Document Loggable properties and methods

### LINKED ISSUE #771: Document loggable properties
## Description

Every loggable property in HOOMD should state that it is loggable in the documentation. They should possibly also state the flags, data type, and default status so that users are aware of how to add them to a `Logger.

## Motivation and context

Users need to know what properties will be logged by a `Logger`.

### PR DESCRIPTION
**Pull request by b-butler**
## Description

Adds a method to `hoomd.logging.Loggable` to add documentation to property and method docstrings that displays that a property is loggable along with its logging type and default status.

## Motivation and context

Resolves #771

## How has this been tested?

Documentation was built locally and reviewed.

## Change log

```
- document loggable quantities in docstring
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Review by joaander — COMMENTED** [review]
Nice! It's great that there is an automated way to do this.

It formats like this: (**Loggable**: type “sequence”, default True)

Can we link Loggable to `hoomd.logging.Logger`?
Also, we call "type" "flag" in `Logger`, we should be consistent here.
Should we always show default=X? Maybe we should not list default when True and only add "not logged by default" when not default.

@bdice do you have any good suggestions for formatting and language to use?

**Comment by bdice** [comment]
> Should we always show default=X? Maybe we should not list default when True and only add "not logged by default" when not default.

I think "default True" is a little confusing. This suggestion might be better, or just specify behavior for both cases: "[not] logged by default."

> Can we link Loggable to `hoomd.logging.Logger`?

This would be nice. However the text is currently bold, and the solutions for "bold links" aren't great. You might have to decide between "link" and "bold." https://docutils.sourceforge.io/FAQ.html#is-nested-inline-markup-possible

**Comment by b-butler** [comment]
@joaander, I have made the changes discussed to the documentation formatting.

**Review by joaander — CHANGES_REQUESTED** [review]
Great! I like the new format.

We just need one minor fix. The loggable output for `state` does not seem to render properly: https://hoomd-blue--829.org.readthedocs.build/en/829/module-hpmc-integrate.html#hoomd.hpmc.integrate.HPMCIntegrator.state

I guess that this is because the `state` docstring is empty so that (Loggable: type="state") gets interpreted with `(Loggable` as the type and `type="state"` as the description.

**Review by joaander — APPROVED** [review]
Thanks!

**Pull request merged**
