### PR TITLE
fix bug to attach active forces on manifolds correctly

### PR DESCRIPTION
**Pull request by SchoeniPhlippsn**
## Description

Fixes a bug when attaching ``hoomd.md.force.ActiveOnManifold``.  Previously the standard active force C++ class was linked instead of the one considering the manifolds. 

## Motivation and context

Bug fix.

## Change log

```
fix bug to attach active forces on manifolds correctly
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Comment by joaander** [comment]
@SchoeniPhlippsn, please rebase this on `trunk-patch`.

**Comment by joaander** [comment]
A rebase is no longer necessary after the v3.3.0 release.

**Review by b-butler — APPROVED** [review]
LGTM

**Comment by b-butler** [comment]
Before merging despite approval make sure to get the git commit history right.

**Pull request merged**
