### PR TITLE
ALJ Debug Assert Failure

### LINKED ISSUE #1282: test_aniso_pair.py in Debug builds
## Description

<!-- Describe the problem. -->

## Script

```bash
$ cmake ~/devel/hoomd -DCMAKE_BUILD_TYPE=Debug -GNinja
$ ninja
$ python3 -m pytest hoomd/md/pytest/test_aniso_pair.py -v -x -ra
```

<!-- Attach any input files needed to execute the script. -->

## Output

<!-- What output did you get? -->
```
==================================================================== test session starts ====================================================================
platform linux -- Python 3.9.5, pytest-7.1.0, pluggy-1.0.0 -- /home/joaander/venv/bin/python3                                                                
cachedir: .pytest_cache                                                                                                                                      
rootdir: /home/joaander/build/hoomd                                                                                                                          
plugins: anyio-3.5.0                                                                                                                                         
collected 38 items                                                                                                                                          
                                                                                                                                                             
hoomd/md/pytest/test_aniso_pair.py::test_mode[CPU-mode0] PASSED                                                                                       [  2%]
hoomd/md/pytest/test_aniso_pair.py::test_mode[CPU-mode1] PASSED                                                                                       [  5%]
hoomd/md/pytest/test_aniso_pair.py::test_rcut[CPU-2.5] PASSED                                                                                         [  7%]
hoomd/md/pytest/test_aniso_pair.py::test_rcut[CPU-4.0] PASSED                                                                                         [ 10%]
hoomd/md/pytest/test_aniso_pair.py::test_rcut[CPU-1.0] PASSED                                                                                         [ 13%]
hoomd/md/pytest/test_aniso_pair.py::test_rcut[CPU-0.01] PASSED                                                                                        [ 15%]
hoomd/md/pytest/test_aniso_pair.py::test_setting_params_and_shape[CPU-Dipole-1] PASSED                                                                [ 18%]
hoomd/md/pytest/test_aniso_pair.py::test_setting_params_and_shape[CPU-GayBerne-1] PASSED                                                              [ 21%]
hoomd/md/pytest/test_aniso_pair.py::test_setting_params_and_shape[CPU-ALJ-1] PASSED                                                                   [ 23%]
hoomd/md/pytest/test_aniso_pair.py::test_setting_params_and_shape[CPU-ALJ-2] PASSED                                                                   [ 26%]
hoomd/md/pytest/test_aniso_pair.py::test_run[CPU-Dipole-1] PASSED                                                                                     [ 28%]
hoomd/md/pytest/test_aniso_pair.py::test_run[CPU-GayBerne-1] PASSED                                                                                   [ 31%]
hoomd/md/pytest/test_aniso_pair.py::test_run[CPU-ALJ-1] PASSED                                                                                        [ 34%]
hoomd/md/pytest/test_aniso_pair.py::test_run[CPU-ALJ-2] PASSED                                                                                        [ 36%]
hoomd/md/pytest/test_aniso_pair.py::test_aniso_force_computes[CPU-ALJ0] PASSED                                                                        [ 39%] 
hoomd/md/pytest/test_aniso_pair.py::test_aniso_force_computes[CPU-ALJ1] PASSED                                                                        [ 42%]
hoomd/md/pytest/test_aniso_pair.py::test_aniso_force_computes[CPU-ALJ2] Fatal Python error: Aborted
                                                                                                                                                             
Current thread 0x00007f1e1fb5a740 (most recent call first):                                                                                                  
  File "/home/joaander/build/hoomd/hoomd/md/force.py", line 84 in energies                                                                                   
  File "/home/joaander/build/hoomd/hoomd/logging.py", line 438 in wrapped_func                 
  File "/home/joaander/build/hoomd/hoomd/md/pytest/test_aniso_pair.py", line 456 in test_aniso_force_computes
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/python.py", line 192 in pytest_pyfunc_call   
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__                                                             
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/python.py", line 1761 in runtest                                                            
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/runner.py", line 166 in pytest_runtest_call                                                 
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall                                                           
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/runner.py", line 259 in <lambda>
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/runner.py", line 338 in from_call
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/runner.py", line 258 in call_runtest_hook                                                   
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/runner.py", line 219 in call_and_report
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/runner.py", line 130 in runtestprotocol                                                     
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/runner.py", line 111 in pytest_runtest_protocol                                             
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall                                                          
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec                                                           
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__                                                             
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/main.py", line 347 in pytest_runtestloop                                                    
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall                                                          
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec                                                           
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__                                                             
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/main.py", line 322 in _main                                                                 
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/main.py", line 268 in wrap_session                                                          
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/main.py", line 315 in pytest_cmdline_main                                                   
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall                                                          
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec                                                           
  File "/home/joaander/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__                                                             
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 164 in main                                                       
  File "/home/joaander/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 187 in console_main
  File "/home/joaander/venv/lib/python3.9/site-packages/pytest/__main__.py", line 5 in <module>
  File "/usr/lib/python3.9/runpy.py", line 87 in _run_code 
  File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main     
zsh: abort (core dumped)  python3 -m pytest hoomd/md/pytest/test_aniso_pair.py -v -x -ra
```

`gdb` reports this assert is failing:
```
#4  0x00007fffb8a589c4 in hoomd::md::EvaluatorPairALJ<3u>::evaluate (this=0x7fffffff81e0, force=..., pair_eng=@0x7fffffff7e08: 0, energy_shift=false, 
    torque_i=..., torque_j=...) at /home/joaander/devel/hoomd/hoomd/md/EvaluatorPairALJ.h:584
584                     assert(success && !overlap);
```

## Expected output

<!-- What output did you expect? -->
All tests pass, as they do in Release builds.

## Configuration

<!-- What is your system configuration? -->

<!-- Remove items that do not apply. -->

Platform:
- Mac
- Linux
- CPU

Installation method:
- Compiled from source

<!-- What software versions do you have? -->

Versions:
- Python version: 3.9.5
- **HOOMD-blue** version: `trunk-patch`

## Developer

<!-- Who should implement the fix? We would welcome your contribution! -->
@tommy-waltmann, please investigate. @vyasr, your input would be appreciated if you have time.

### PR DESCRIPTION
**Pull request by tommy-waltmann**
## Description

In debug builds, there were some ALJ tests which detected overlaps in the test configuration, causing the test suite to crash. I investigated the tests and found that the overlap detection code can give both false positives and false negatives. With that in mind, this PR does not actually fix the overlap detection code, it simply changes the test configurations so there are no overlaps in the test configurations and changes the parameter choices so the tests pass.

A more in-depth attempt to fix the overlap detection code would take a large amount of effort due to the nature of the GJK algorithm.

## Motivation and context

This issue was found in #1282 , and the goal of this PR is to just be able to run all the tests in debug mode without failing.

Resolves #1282 

## How has this been tested?

As long as existing tests pass with the new configurations, we should be good to go.

## Change log

```
Fix ALJ testing parameters.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Review by b-butler — APPROVED** [review]
@tommy-waltmann looks good to me. Can you make an issue regarding the need to change the overlap check or its broken status? A code TODO would also be helpful for future developers as well.

**Comment by tommy-waltmann** [comment]
We already have a comment above the offending assert that the overlap check may be invalid. I can make an issue about it though.

**Comment by joaander** [comment]
@seoulfood we would appreciate your review.

**Comment by joaander** [comment]
@seoulfood thanks for trying, but I am not going to leave this open indefinitely.

**Pull request merged**
