### PR TITLE
Improve depletants and clusters

### PR DESCRIPTION
**Pull request by jglaser**
## Description

**WORK IN PROGRESS**

New depletant features (ntrial acceptance rule on CPU, clusters updater w/depletants on GPU), based against the HOOMD3 branch (`hpmc_integrator_api`). Remove quermass.

## Motivation and Context

Aiming to get new depletant features into HOOMD3, while resolving merge conflicts early on.

## How Has This Been Tested?

Current unit tests.

## Change log

N/A

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/hoomd-blue/blob/master/sphinx-doc/credits.rst).

### CODE REVIEW

**Comment by joaander** [comment]
I merged `next` through `hpmc_integrator_api` up into this branch so that it can be reviewed independently from the other PRs that were already included in it.

Is this something I should review now or wait until it is complete?

**Comment by jglaser** [comment]
I am currently still working on the base branch `depletants_new` and will create a separate PR against next, possibly eliminating the need for this PR. It will also include `update.clusters()` (GPU) related changes which are in progress

**Comment by joaander** [comment]
OK, hopefully there are minimal/no changes to the Shape header files when merging up. Managing their merge conflicts is starting to get very time consuming.

**Comment by joaander** [comment]
Closing, @jglaser is working on a different version of this branch based off `next`.

**Pull request closed without merging**
