### PR TITLE
Add needed thrust includes.

### PR DESCRIPTION
**Pull request by joaander**
## Description

Add needed thrust includes.

## Motivation and context

This fixes compile errors with the next CUDA release.

## How has this been tested?

Peng Wang at NVIDIA tested these changes with an unspecified newer version of CUDA.

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Comment by bdice** [comment]
@joaander Thrust 1.16 (released a while ago but not yet in a CUDA toolkit release) removed some internal header inclusions that some applications had implicitly relied on (as transitive includes). You can probably build with Thrust 1.16 or 1.17 from GitHub and see the errors.

**Review by tommy-waltmann — APPROVED** [review]

**Comment by bdice** [comment]
@joaander I ran a "thrust include finder" script that I was using for another project, which located a few more missing includes. I will push those to this PR. It's not a large changeset but should make this a little more complete.

**Review by bdice — APPROVED** [review]
Approving -- feel free to accept or reject the commit I added here. The includes I added may not be needed to compile because of transitive includes in Thrust's internals, but that's not desirable and should be replaced with explicit includes (include what you use). My additional commit makes the includes explicit for all the used Thrust features.

**Comment by joaander** [comment]
> Approving -- feel free to accept or reject the commit I added here. The includes I added may not be needed to compile because of transitive includes in Thrust's internals, but that's not desirable and should be replaced with explicit includes (include what you use). My additional commit makes the includes explicit for all the used Thrust features.

Thanks for the additional includes. Those will help future proof this code against compiler errors with new thrust releases.

**Pull request merged**
