### PR TITLE
Prepare to release v3.4.0.

### PR DESCRIPTION
**Pull request by joaander**
## Description

Changes needed to release v3.4.0.

## Motivation and context

Make recent changes available to users.

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/trunk-minor/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Review by AlainKadar — APPROVED** [review]
LGTM

**Comment by joaander** [comment]
Here is the `hoomd-benchmarks` run using:

* f1e47ea
* glotzerlab/hoomd-benchmarks@a7e625c2063829daba5a74e52558bd8b8da349ea

GPU: GV100
`python3 -m hoomd_benchmarks --device GPU --output out.dat --name "${name}" --repeat 40 -v`

```
                                      3.3.0         3.4.0
HPMCSphere                     1.029362e+03  8.181010e+02
MDPairLJ                       3.029206e+03  3.118265e+03
MDPairWCA                      6.055511e+03  6.253793e+03
MicrobenchmarkEmptySimulation  1.660807e+07  1.603045e+07
MicrobenchmarkCustomTrigger    2.708251e+06  2.580989e+06
MicrobenchmarkCustomUpdater    4.428889e+06  4.320495e+06
MicrobenchmarkCustomForce      0.000000e+00  0.000000e+00
MicrobenchmarkGetSnapshot      6.824958e+01  6.753468e+01
MicrobenchmarkSetSnapshot      5.447870e+01  5.320749e+01
```

CPU: AMD Ryzen Threadripper 3960X 24-Core Processor
`mpirun -n 24 python3 -m hoomd_benchmarks --device CPU --output out.dat --name "${name}" --repeat 40 -v`

```
                                      3.3.0         3.4.0
HPMCSphere                     3.406701e+02  3.484100e+02
MDPairLJ                       2.596391e+02  2.687674e+02
MDPairWCA                      1.186747e+03  1.185968e+03
MicrobenchmarkEmptySimulation  2.113898e+07  2.133463e+07
MicrobenchmarkCustomTrigger    3.495592e+06  3.424230e+06
MicrobenchmarkCustomUpdater    6.862087e+06  6.787280e+06
MicrobenchmarkCustomForce      3.925985e+03  3.911224e+03
MicrobenchmarkGetSnapshot      2.213407e+01  2.176707e+01
MicrobenchmarkSetSnapshot      2.047383e+01  2.049648e+01
```

**Comment by joaander** [comment]
As expected, the MD benchmarks increase performance slightly as `hoomd-benchmarks` now waits for autotuning to complete before measuring. 

I did not expect the performance drop in HPMC. These results are repeatable. I'm not going to delay the release over this, but will file an issue and investigate later: #1381

**Comment by joaander** [comment]
The slowdown appears to be in the `hpmc_narrow` kernel tuning. Here is the HPMCSphere tuning from v3.3:
```
notice(4): Autotuner hpmc_narrow found optimal parameter 64000401
```
And from the v3.4 release candidate:
```
notice(4): Autotuner hpmc_narrow found optimal parameter (800,1,2,) with a performance spread of 784%.
```

From a different benchmark that shows faster performance:
```
notice(4): Autotuner hpmc_narrow found optimal parameter 96000101
notice(4): Autotuner hpmc_narrow found optimal parameter (32,1,1,) with a performance spread of 2815%.
```

**Comment by joaander** [comment]
HPMC performance issue fixed in f905a47:
```
python3 -m hoomd_benchmarks.hpmc_sphere --device GPU -v                                                                                            [warmup-until-autotuned]
Using existing initial_configuration_cache/hard_sphere_64000_1.0_3.gsd
Running HPMCSphere benchmark
.. warming up for 1000 steps
.. running for 1000 steps 1 time(s)
.. 1032.659402596209 trial moves per second per particle
1032.659402596209
```

**Pull request merged**
