### PR TITLE
Make ParticleFilter objects picklable.

### PR DESCRIPTION
**Pull request by b-butler**
## Description

Makes `ParticleFilter` objects picklable using Python using __reduce__ to reconstruct the object. This prevents problems in the set filters and prevents needing to construct getter and setters in C++ to be able to pickle through pybind11's facilities.

## Motivation and context

Moving towards most HOOMD-blue object being picklable for restartability.

## How has this been tested?

Has been tested locally. Will be tested through unit tests before merging.

## Change log

```
Added: ParticleFilters are picklable.
```

## Checklist:

- [x] I have reviewed the [**Contributor Guidelines**](https://github.com/glotzerlab/hoomd-blue/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**HOOMD-blue Contributor Agreement**](https://github.com/glotzerlab/hoomd-blue/blob/master/ContributorAgreement.md).
- [x] My name is on the list of contributors (`sphinx-doc/credits.rst`) in the pull request source branch.

### CODE REVIEW

**Review by joaander — APPROVED** [review]
Thanks! Looks good to me. 
@bdice or @vyasr is this a good use of the pickling APIs?

**Comment by vyasr** [comment]
This looks fine to me. @b-butler I assume the reason you went for using `__reduce__` rather than the higher level `__getstate__` and `__setstate__` APIs is that you need to actually call the constructor in order to call all parent constructors (since these use multiple inheritance) and propagate the data down to the C++ mirror classes?

**Comment by vyasr** [comment]
Posting here for future reference: @b-butler and I have talked and I'm on board with the changes here as well as in #885 and #886.

**Pull request merged**
