### PR TITLE
allow unsafe bond removal

### PR DESCRIPTION
**Pull request by InnocentBug**
Description and motivation is detailed in #650

### CODE REVIEW

**Comment by joaander** [comment]
@jglaser What do you think?

**Comment by joaander** [comment]
@jglaser any thoughts on this PR?

**Comment by InnocentBug** [comment]
Any chance to move forward with this PR?

**Comment by joaander** [comment]
@jglaser developed the MPI communication routines for bonds. I am waiting for his review.

**Comment by joaander** [comment]
I haven't head from @jglaser on this. My opinion is that any changes in this direction should be complete and allow for efficient bond addition and removal.

**Pull request closed without merging**
